# Generated by Django 2.0.2 on 2018-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shooter',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='shooter',
            name='first_name',
        ),
    ]
