# Generated by Django 2.0 on 2018-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20180219_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Disziplin',
                'verbose_name_plural': 'Disziplinen',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='discipline',
            field=models.CharField(default='(Training)', max_length=255),
        ),
    ]
